package churn

// Port is a one-way communication channel presented by a node
//
// Ports come in two basic flavours, in and out:
// - out ports generate data that can move through the graph
// - in ports respond to data generated by output ports
type Port struct {
	Name string

	// either a *churncore.Sender or *churncore.Receiver
	// depending on if this is an in or out port
	core interface{}
}

// PortSlice provides helper methods for working with
// slices of ports
type PortSlice []*Port

// FindByName returns the first port in this slice with the given
// name, or nil if no port has such a name
func (p PortSlice) FindByName(name string) *Port {

	for _, port := range p {
		if name == port.Name {
			return port
		}
	}
	return nil

}
