package churn

// Port is a one-way communication channel presented by a node
//
// Ports come in two basic flavours, in and out:
// - out ports generate data that can move through the graph
// - in ports respond to data generated by output ports
type Port struct {
	Name string

	core PortCore
}

// Core returns the business logic core of this port
func (p *Port) Core() PortCore { return p.core }

// PortCore contains the underlying business logic
// of a port, and is either an In- or OutPortCore.
//
// Not all methods apply to all cores, and the underlying
// type of the core may need to be understood in order to
// avoid run-time panics.
type PortCore interface {
	AddReceiver(*Port) error
}
